### ISSUE TITLE
Padding is incorrectly included in the draw rect

### ISSUE THREAD

**Issue by dtaylorus** [chrfalch/NControl#10]
If I add padding to the NControlView, the rect parameter of the Draw method includes the padding.

This seems incorrect to me, since my understanding of padding is that you don't draw on it.

Additionally, this is not easy to correct by simply subtracting the padding from the rect, since the units have changed. For example, on my Android test device, a padding thickness of 50 in the control becomes 100 in the draw rect size, and I'm not sure how to undo this conversion in a device-independent way.

It sure would be nice if NControlView correctly removed the padding from the rect to avoid this complexity.

Thanks!

**Comment by dtaylorus** [comment]
Fyi, here's what I did as a workaround at the start of the Draw method:

```
// Account for padding
if (this.Height > 0)
{
    double yScale = rect.Height / this.Height;
    rect.Y += (this.Padding.Top * yScale);
    rect.Height -= (this.Padding.VerticalThickness * yScale);
}
if (this.Width > 0)
{
    double xScale = rect.Width / this.Width;
    rect.X += (this.Padding.Left * xScale);
    rect.Width -= (this.Padding.HorizontalThickness * xScale);
}
```

**Comment by chrfalch** [comment]
Nice! If you'd like to create a pull request with this change I'd be happy to merge it.

**Comment by chrfalch** [comment]
Closing - waiting for merge request.
