### ISSUE TITLE
TouchesEnded is not called on iOS

### ISSUE THREAD

**Issue by dtaylorus** [chrfalch/NControl#16]
TouchesEnded is invoked after TouchesBegan on Android, but not on iOS.

I noticed that all of the demo controls are either treating TouchesCancelled the same as TouchesEnded, or are only using TouchesBegan, which explains why the demos work on both Android and iOS, but my code that is working on Android does not work on iOS.

The behavior that I expect is that TouchesCancelled should be handled differently than TouchesEnded and should not invoke, for example, a Click event.

**Comment by chrfalch** [comment]
You are correct - the problem is that on iOS a button seems to be using some additional magic to detect touches - relying on touchesbegan/cancel/ended does not make for a good experience. TouchesCancelled is called when you have a touchesbegan and are not moving the touch point. If you'd like to experiment with this, please go ahead and see - you can create a merge request.

**Comment by chrfalch** [comment]
Closed due to missing answer

**Comment by dtaylorus** [comment]
Hi Christian,

I didn't get a chance to integrate a solution into your project, but as a quick-and-dirty fix I subclassed NControl (as XControl) and implemented the following renderer on iOS:

```
public class XControlRenderer : NControlViewRenderer
{
    private UITouchesGestureRecognizer _gestureRecognizer;

    public XControlRenderer()
    {
    }

    protected override void OnElementChanged(
        ElementChangedEventArgs<NControl.Abstractions.NControlView> e)
    {
        base.OnElementChanged(e);

        if (e.OldElement != null)
        {
            if (null != this._gestureRecognizer)
            {
                this.RemoveGestureRecognizer(this._gestureRecognizer);
                this._gestureRecognizer = null;
            }
        }

        if (e.NewElement != null)
        {
            if ((null == this._gestureRecognizer) && (null != this.NativeView))
            {
                this._gestureRecognizer = new UITouchesGestureRecognizer(e.NewElement, this.NativeView);
                this.NativeView.AddGestureRecognizer(this._gestureRecognizer);
            }
        }
    }

    public override void TouchesBegan(Foundation.NSSet touches, UIEvent evt)
    {
        // Ignore buggy Xamarin touch events on iOS
    }

    public override void TouchesEnded(Foundation.NSSet touches, UIEvent evt)
    {
        // Ignore buggy Xamarin touch events on iOS
    }

    public override void TouchesCancelled(Foundation.NSSet touches, UIEvent evt)
    {
        // Ignore buggy Xamarin touch events on iOS
    }

    public override void TouchesMoved(Foundation.NSSet touches, UIEvent evt)
    {
        // Ignore buggy Xamarin touch events on iOS
    }

    private sealed class UITouchesGestureRecognizer : UIGestureRecognizer
    {
        private NControlView _element;
        private UIView _nativeView;

        public UITouchesGestureRecognizer(
            NControlView element,
            UIView nativeView)
        {
            if (null == element)
            {
                throw new ArgumentNullException("element");
            }

            if (null == nativeView)
            {
                throw new ArgumentNullException("nativeView");
            }

            this._element = element;
            this._nativeView = nativeView;
        }

        private IEnumerable<NGraphics.Point> GetTouchPoints(
            Foundation.NSSet touches)
        {
            var points = new List<NGraphics.Point>((int)touches.Count);
            foreach (UITouch touch in touches)
            {
                CGPoint touchPoint = touch.LocationInView(this._nativeView);
                points.Add(new NGraphics.Point((double)touchPoint.X, (double)touchPoint.Y));
            }

            return points;
        }

        public override void TouchesBegan(Foundation.NSSet touches, UIEvent evt)
        {
            base.TouchesBegan(touches, evt);

            var points = GetTouchPoints(touches);

            this._element.TouchesBegan(points);
        }

        public override void TouchesMoved(Foundation.NSSet touches, UIEvent evt)
        {
            base.TouchesMoved(touches, evt);

            var points = GetTouchPoints(touches);

            this._element.TouchesMoved(points);
        }

        public override void TouchesEnded(Foundation.NSSet touches, UIEvent evt)
        {
            base.TouchesEnded(touches, evt);

            var points = GetTouchPoints(touches);

            this._element.TouchesEnded(points);
        }

        public override void TouchesCancelled(Foundation.NSSet touches, UIEvent evt)
        {
            base.TouchesCancelled(touches, evt);

            var points = GetTouchPoints(touches);

            this._element.TouchesCancelled(points);
        }
    }
}
```

**Comment by chrfalch** [comment]
Thanks :-) When testing this I couldn't see any difference from the previous behaviour? 

The problem I have is that while on Android and WinPhone touches is passed through views if the NControlView does not have a touch event assigned, while on iOS this does not happen. Your solution does not solve this problem?

**Comment by dtaylorus** [comment]
The NControl subclasses that worked fine in my Android app didn't work on iOS because there was no TouchesEnded event. I'm not sure why, but the event sequence was TouchesBegan followed by TouchesCanceled, no matter how I touched the button. TouchesEnded was never called. Additionally, if I remember right, TouchesBegan was delayed so I had to hold the button for a little while before I received the event.

When I switched to the GestureRecognizer solution, everything worked as expected.

I think if you modify your demo controls to treat TouchesCanceled as a cancelation (instead of treating TouchesCanceled the same as TouchesEnded) you should be able to see the difference.

Thanks for looking into this!

**Comment by chrfalch** [comment]
I've seen that if you move the touch pointer (finger or mouse) a little bit you will get the TouchesEnded in the original implementation, but I agree with you that your solution seems to be better. Will try to integrate it. Thanks for suggesting a fix!
