### ISSUE TITLE
Controls not working in Ad Hoc builds

### ISSUE THREAD

**Issue by JoshuaNovak919** [chrfalch/NControl#21]
When I run a debug view on my phone or in the simulator my controls work great, but when I make an Ad Hoc build and run that on my phone they don't show up. Anyone have any ideas?

**My Controls code:**

```
using NControl.Abstractions;
using Xamarin.Forms;
using NGraphics;
using System.Diagnostics;
using System.Collections.Generic;

namespace MyApp.Controls
{
    public class HalfRibbon : NControlView
    {
        public static BindableProperty EndPercentageProperty = 
            BindableProperty.Create<HalfRibbon, double> (p => p.EndPercentage, 0.07, 
                BindingMode.OneWay, null, EndPercentageChanged);

        public double EndPercentage 
        {
            get { return (double)GetValue(EndPercentageProperty); }
            set { SetValue(EndPercentageProperty, value); }
        }

        private static void EndPercentageChanged(BindableObject bindable, double oldValue, double newValue)
        {
            (bindable as HalfRibbon).Invalidate();
        }

        public static new BindableProperty BackgroundColorProperty = 
            BindableProperty.Create<HalfRibbon, Xamarin.Forms.Color> (
                p => p.BackgroundColor, Xamarin.Forms.Color.Transparent, BindingMode.OneWay, null, BackgroundColorChanged);

        public new Xamarin.Forms.Color BackgroundColor
        {
            get { return (Xamarin.Forms.Color)GetValue(BackgroundColorProperty); }
            set { SetValue(BackgroundColorProperty, value); }
        }

        private static void BackgroundColorChanged(BindableObject bindable, Xamarin.Forms.Color oldValue, Xamarin.Forms.Color newValue)
        {
            (bindable as HalfRibbon).Invalidate();
        }

        public HalfRibbon ()
        {
        }

        public override void Draw(NGraphics.ICanvas canvas, NGraphics.Rect rect)
        {
            base.Draw(canvas, rect);

            var backgroundBrush = new SolidBrush(new NGraphics.Color(BackgroundColor.R,
                BackgroundColor.G, BackgroundColor.B, BackgroundColor.A));

            var width = (WidthRequest > 0)? WidthRequest : rect.Width;
            var ribbonWidth = Math.Ceiling(width * EndPercentage);
            var height = (HeightRequest > 0)? HeightRequest : rect.Height;

            canvas.DrawPath(new PathOp []{ 
                new MoveTo(0, 0),
                new LineTo(width, 0),
                new LineTo(width - ribbonWidth, height / 2),
                new LineTo(width, height),
                new LineTo(0, height),
                new LineTo(0, 0),
                new ClosePath()
            }, null, backgroundBrush);
        }
    }
}
```

**Comment by JoshuaNovak919** [comment]
Looks like this has to do with `Linker Options`. Once I set the `Linker Options > Linker Behaviour` to `Don't link` it worked. Not sure if this is a bug, or just needs to be put in the docs.

**Comment by chrfalch** [comment]
This is a common Xamarin issue - try setting the linker behavior to "SDK Assemblies" to reduce the app size.

**Comment by JoshuaNovak919** [comment]
I am still having this issue with some projects. It looks like the control needs `[Preserve(AllMembers=true)]` in iOS and Android etc. 

And also the init function should be changed to this:

```
public async static void Init()
{
  var temp = DateTime.Now;
}
```

These changes are based off an issue in a simliar nuget: jamesmontemagno/Xamarin.Plugins#79

**Comment by chrfalch** [comment]
@JoshuaNovak919: If you want you can create a pull request with these issues addressed - would be happy to put them in!

**Comment by JoshuaNovak919** [comment]
@chrfalch I would have, but i'm on a mac so it would make me change all the file paths to make it work. I can try setting up the old windows machine I have tomorrow at some point, but I figured someone else could do this six times by the time I do all that. If there is a good way to modify this and test it on a mac without it changing paths etc please let me know and I can do it right now.

**Comment by chrfalch** [comment]
I'm swapping back and forth between my Mac and Windows machine without any troubles with paths - Feel free to also write up a detailed description and we'll see if anyone wants to help!

**Comment by JoshuaNovak919** [comment]
@chrfalch I tested a release build with your demo iOS project and it didn't work. I made the changes it and worked great. I'll make a pull request now. I only made the changes for Android and iOS since I haven't worked with Windows phone and i'm not sure if it even has the same issue.

**Comment by JoshuaNovak919** [comment]
@chrfalch Hopefully I did that correctly. It's the first time i've done a pull request lol.

**Comment by chrfalch** [comment]
Looks good, @JoshuaNovak919  :-) Thanks!

**Comment by chrfalch** [comment]
Closed with by merging Pull Request.
