### ISSUE TITLE
NControlView.BackgroundColor property does not honor Alpha channel value

### ISSUE THREAD

**Issue by dtaylorus** [chrfalch/NControl#28]
The alpha channel of the background color property of NControlView is thrown away when setting the color for the canvas background color in the Draw method.

This was driving me crazy until I finally realized that BackgroundColor is overridden by NControlView!

**Comment by chrfalch** [comment]
Yes, that's true - the reason being that we need to invalidate when changing the background. Please feel free to create a pull request with suggested changes!
