### ISSUE TITLE
Setting Android background color causes CircularButtonControl to not draw correctly

### ISSUE THREAD

**Issue by tbaggett** [chrfalch/NControl#31]
Thanks for a great lib! This may be an NGraphics problem, but I saw it while using your library so I will start with you. If I specify a background color, for example in your "Theme.NewSolution" custom theme like so:

```
    <item name="android:background">#ff0000</item>
```

None of the custom drawing commands appear to be executed, although I have stepped through the code while debugging and confirmed that they are. See attached images from before and after adding the background setting to your theme.

BEFORE:
![1 - before](https://cloud.githubusercontent.com/assets/1326678/8491522/28f1c0ae-2100-11e5-93ce-2ebc396645fe.png)

AFTER:
![2 - after](https://cloud.githubusercontent.com/assets/1326678/8491523/28f3450a-2100-11e5-9ca6-2367c70537fc.png)

**Comment by BlueRaja** [comment]
Possibly related to https://github.com/chrfalch/NControl/issues/28 ?

**Comment by chrfalch** [comment]
Maybe - are you testing this with the latest version.

**Comment by tbaggett** [comment]
This was tested with version 0.5.981. I downloaded the latest source zip file and used it to verify what I was seeing in my project on the evening of July 2nd.

**Comment by chrfalch** [comment]
Ok, need to investigate this further.

**Comment by chrfalch** [comment]
A new version (0.6.18) has been uploaded to NuGet that should address this issue.

**Comment by BlueRaja** [comment]
? This issue is about Android, not Windows Phone

**Comment by chrfalch** [comment]
Hi, that's true, my mistake - comment is updated.
