### ISSUE TITLE
GestureRecognizers don't seem to be called anymore

### ISSUE THREAD

**Issue by JoshuaNovak919** [chrfalch/NControl#32]
After the newest update all the `GestureRecognizers` I called on my NControl elements no longer work. Any idea why this would have changed?

**Comment by chrfalch** [comment]
Hi Joshua,

I made a simple example with NControl version 0.5.981 where I use a gesture recognizer that is working fine. Could you try to isolate the problem and reproduce it in a simple example?

``` c#
            var label = new Label {
                XAlign = Xamarin.Forms.TextAlignment.Center,
                Text = "NControl"
            };

            var testControl = new NControlView{
                HeightRequest = 44,
                BackgroundColor = Xamarin.Forms.Color.Red,
            };

            testControl.GestureRecognizers.Add(new TapGestureRecognizer{
                Command = new Command(() => {
                label.Text = "Clicked";
                })
            });
```

**Comment by JoshuaNovak919** [comment]
It turns out I just had to change the code in my control a bit. I originally had to add the `TouchesBegan` class and return true to get it to call the event, changing it to false works now.

I originally had:

```
public override bool TouchesBegan(System.Collections.Generic.IEnumerable<NGraphics.Point> points)
{
    base.TouchesBegan(points);
    return true;
}
```

I changed it to this and now it works:

```
public override bool TouchesBegan(System.Collections.Generic.IEnumerable<NGraphics.Point> points)
{
    base.TouchesBegan(points);
    return true;
}
```

**Comment by BlueRaja** [comment]
You posted the same code twice?
