### ISSUE TITLE
NControl crashes on Windows Phone

### ISSUE THREAD

**Issue by helusoft** [chrfalch/NControl#33]
Hi,
NControl is great and i like it, but now, it crashes on WindowsPhone.
Even if i only call
var view = new NControlView();
The App runs into (App.xaml.cs)

```
// Code to execute if a navigation fails
private void RootFrame_NavigationFailed(object sender, NavigationFailedEventArgs e)
{
    if (Debugger.IsAttached)
    {
        // A navigation has failed; break into the debugger
```

STOPPED HERE Debugger.Break();
        }
   }

It works fine on Android and iOS
What happens ??

I'm using XF 1.4.4.6392 and NControl 0.5.981

**Comment by chrfalch** [comment]
A new version (0.6.18) has been uploaded to NuGet that should be working on Windows Phone.
