### ISSUE TITLE
what's happening with SVG?

### ISSUE THREAD

**Issue by georgejecook** [chrfalch/NControl#36]
Are you supporting that yet? As per : https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG

**Comment by chrfalch** [comment]
Hi, NControl only supports what https://github.com/praeclarum/NGraphics supports. When they update with new releases we try to follow, but we might be a few steps behind from time to time. Feel free to download the sources and see if you can create a pull request!
