### ISSUE TITLE
Update points

### ISSUE THREAD

**Issue by JoshuaNovak919** [chrfalch/NControl#4]
Is there a way to update points? I made a line with endpoint variables that I invalidate and it doesn't seem to update. I'm not sure if i'm doing it wrong, or if there isn't a way to do this.

**Variable definitions:**

```
private double _endX = 0;
public double EndX { 
    get 
    { 
        return _endX; 
    }
    set 
    { 
        _endX = value;
        Invalidate();
    }
}

private double _endY = 0;
public double EndY { 
    get 
    { 
        return _endY; 
    }
    set 
    { 
        _endY = value;
        Invalidate();
    }
}
```

**Line:**
`canvas.DrawLine (20, 20, EndX, EndY, Colors.Blue, 2);`

**Comment by chrfalch** [comment]
If the line `canvas.DrawLine (20, 20, EndX, EndY, Colors.Blue, 2)´´´ exists in the DrawFunction or in an overridden Draw function,`Invalidate()``` should be the correct way to redraw when changing the points. Please provide me with a simple project that reproduces the problem, without it it is really hard to find out whats wrong.

**Comment by JoshuaNovak919** [comment]
Actually, it looks like it does work. I just didn't realize it was calling the draw function again every time and I had dimensions resetting in the draw call.

On another note, is there a good way to go about drawing a circle that has changing points? I need to make a circle percentage indicator and i've been messing around with `CurveTo`, but i'd have to calculate control points each time and i'm not sure if there is a way to animate between the points.

**Comment by chrfalch** [comment]
Use animations to rotate and/or transform. That's always faster than redrawing.

**Comment by chrfalch** [comment]
Look at the progress control sample to see how it can be done.
