### ISSUE TITLE
Impossible to draw NGraphics images using NControl

### ISSUE THREAD

**Issue by chrfalch** [chrfalch/NControl#41]
To be able to create and draw images we need access to the current platform. This is not exposed by the NControl renderers and NControl abstraction and should be added.

**Comment by anton-makarevich** [comment]
Hi Christian, I added this in my local fork for windows and android when worked on the project where i had to export some images to pdf several months ago, but my solution is not very polished and has some issues... I can share it or create pullrequest, but it based on some outdated version. Let me know if this will be helpful

**Comment by chrfalch** [comment]
I'll commit a change I started working on were the abstraction exposes the underlying platform - that should give us access to what we need in NGraphics. Is this in the line of what you did?

**Comment by anton-makarevich** [comment]
I can check code in several hours. the main change was - NGrahics has 2 canvas abstractions - one like ICanvasCanvas and another IImageCanvas with underlaying bitmaps support (maybe not exact as typing by memory), so I changed canvases used in platform/renderers to those supporting bitmaps, but i also needed to draw images on canvas as well...

**Comment by chrfalch** [comment]
I need to make sure this works on Windows as well - we took a few shortcuts
when implementing the Canvas based renderer there.

**Comment by anton-makarevich** [comment]
Windows is the easiest platform for that -  you have a separate winstoreplatform implementation in NControl, so it should be possible to save any UI element to bitmap using RenderTargetBitmap

**Comment by chrfalch** [comment]
Moved to #52
