### ISSUE TITLE
Handle click with scroll view

### ISSUE THREAD

**Issue by JoshuaNovak919** [chrfalch/NControl#43]
Does anyone know the best way to handle the click event when the element is in a scrollview? Right now if I touch on the object I am using NControl for and try to scroll the screen it does not scroll and the touch registers even if I move my finger away from the button.

**Comment by JoshuaNovak919** [comment]
Anyone?

**Comment by chrfalch** [comment]
This is definitely a challenge - try doing the same thing on iOS and you
will see similar issues.

What I've done previously is to use a transparent button to handle clicks
(no individual touch events then, sorry) when my custom control is in a
list.

Chris

**Comment by JoshuaNovak919** [comment]
Added a `TapGestureRecognizer` seems to work, but I still want trigger an animation on the `TouchesBegan` and `TouchesEnded` events. If I do though, it steals the event from the scrollview and doesn't scroll. Anyway to stop it from stealing the event?

**Comment by chrfalch** [comment]
No, that's the big here. The list (especially on iOS) contains lots of
custom touch code to handle cases where you first tap on an item and then
start dragging etc. See if you can test this on iOS directly first - that's
often (from my experience) where these problems originate from.

**Comment by JoshuaNovak919** [comment]
I got it to work. I ended up using MR.Gestures (you have to buy it, but it's only 12 bucks).

All I had to do after setting it up was add the events I wanted to handle:

```
_stackLayout.Down += OnTouchDown;
_stackLayout.Up += OnTouchUp;
_stackLayout.Tapped += OnTapped;
```

Now scrolling works and my events run properly. This is a good enough work around for now I guess.

**Comment by chrfalch** [comment]
Great, thanks!
