### ISSUE TITLE
CircularButtonControl not showing the Icon on Android

### ISSUE THREAD

**Issue by jesusgarza** [chrfalch/NControl#44]
I am using the CircularButtonControl and ProgressControl from XAML and the icon shows correctly on iOS, but not on Android. This is the ContentPage

``` javascript
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:qcontrols="clr-namespace:NGraph1;assembly=NGraph1"
    x:Class="NGraph1.TestPage"
    Title="Test Title">
    <ContentPage.Content>
            <StackLayout Orientation="Vertical" Padding="5,5,5,0" >
                <qcontrols:ProgressControl BackgroundColor="Green" CornerRadius="80" WidthRequest="100" HeightRequest="100" />
                <qcontrols:CircularButtonControl FAIcon="{x:Static qcontrols:FontAwesomeLabel.FAPlay}"  />
            </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

Any ideas why?

**Comment by chrfalch** [comment]
Which CircularButtonControl and ProgressControl are you using - or is this something you have built yourself?

**Comment by jesusgarza** [comment]
I'm using the ones on the demo project, as a way to get to know NControl:
https://github.com/chrfalch/NControl/blob/develop/NControlDemo/NControlDemo.FormsApp/Controls/ProgressControl.cs

I also added in the ProgressControl constructor this code, to start the animation on a click:

``` javascript
            var gestureRecognizer = new TapGestureRecognizer();

            gestureRecognizer.Tapped += (s, e) => {
                this.Start();
            };

            this.GestureRecognizers.Add (gestureRecognizer);
```

It does work, but in Android I don't see the icon. Strange, ¿no?

**Comment by chrfalch** [comment]
Could it be that you have forgotten to include the Font Awesome fonts in your project?

**Comment by jesusgarza** [comment]
Well, something like that: I didn't include the FontAwesomeLabelRenderer. Thanks for taking the time Christian!
