### ISSUE TITLE
IsVisible changes should call Invalidate() ?

### ISSUE THREAD

**Issue by bryancostanich** [chrfalch/NControl#45]
I could be doing something wrong here, but it seems that if you have a custom NControlView, and it's initially set to IsVisible = false, then if you change it to true, then the control will not render because no Draw() call is made.

So perhaps, NControlView needs to listen to visibility changes and make a call to Invalidate() when it it goes to true?

**Comment by bryancostanich** [comment]
The following code seems to fix it (in my custom NControlView):

``` csharp
        protected override void OnPropertyChanged (string propertyName)
        {
            base.OnPropertyChanged (propertyName);

            if (propertyName == "IsVisible") {
                if (this.IsVisible) {
                    this.Invalidate ();
                }
            }
        }
```

**Comment by chrfalch** [comment]
Hi, thanks for the suggestion - this seems to be correct. If you want to you can create a pull request and submit it (there are several good tutorials available), or I will try to integrate this within a week or two.

(A quick comment on your suggestion: 

``` csharp
if (propertyName == VisualElement.IsVisibleProperty.PropertyName) 
```

This way we get compile time errors if the property name changes.

**Comment by KirillAshikhmin** [comment]
If you change the IsVisible the parent View is also not called Draw, nested NControlView.
Scenario:
1. When you open a page with NControlView her all the content is hidden.
2. OnAperring put IsVisible = true at the root View.
3. NControlView does not appear (Draw is not called)

Versions:
NControl: 0.7.1
Xamarin Forms: 2.0.0.6490

Possible fixes in the current version:
1. Call the Invalidate method after step 2.
2. Add in NControlView child and added:
  protected override void LayoutChildren (double x, double y, double width, double height)
         {
             base.LayoutChildren (x, y, width, height);
             Invalidate ();
         }

**Comment by bryancostanich** [comment]
did this get fixed? I see the issue is closed, but i don't see a change in the NControlView.cs file.

**Comment by chrfalch** [comment]
Hi,

Fixed, but not yet released - been busy testing/verifying

Chris

**Comment by bryancostanich** [comment]
very cool. can't wait!

**Comment by chrfalch** [comment]
Also updated to XF 2.0, hope that's ok.

**Comment by bryancostanich** [comment]
fantastic. can't wait to see it.
