### ISSUE TITLE
Win RT version - Renderer crashes when view gets removed from page

### ISSUE THREAD

**Issue by soernt** [chrfalch/NControl#56]
Within NControlViewRenderer.OnElementChanged the renderer crashes when setting the native control `SetNativeControl(ctrl);` while the view is getting removed from the page.

I changed the implementation to catch the situation when OnElementChanged is called while the view is going to be removed:

```
 protected override void OnElementChanged(ElementChangedEventArgs<NControlView> e)
    {

      base.OnElementChanged(e);

      if (e.OldElement != null)
      {
        e.OldElement.OnInvalidate -= HandleInvalidate;
      }

      if (e.NewElement != null)
      {
        e.NewElement.OnInvalidate += HandleInvalidate;
      }

      // I added these three lines.
      if ((e.OldElement != null) && (e.NewElement == null) && (Control == null))
      {
        return;
      }

      if (Control == null)
      {
        var ctrl = new NControlNativeView();
        Canvas = new Canvas();
        Border = new Border
        {
          Child = Canvas,
        };

        ctrl.Children.Add(Border);

        SetNativeControl(ctrl);

        UpdateClip();
        UpdateInputTransparent();
      }

      RedrawControl();
    }
```

Kind regards,
Sörnt

**Comment by chrfalch** [comment]
Thanks for the code - would it be possible for you to create a quick pull request - promise I will merge it quickly since its a simple fix.

**Comment by soernt** [comment]
Within my pull request " Initial Windows Phone RT Support. #51" I just added another commit with the fixed to: 
a) Win RT version - Renderer crashes when view gets removed from page
b) Windows RT version - CanvasCanvas.MeasureText is not working correctly

hope that helps

**Comment by TomSoderling** [comment]
This should be fixed now, the PR is closed https://github.com/chrfalch/NControl/pull/51

**Comment by slava-osipov-qs** [comment]
> promise I will merge it quickly since its a simple fix.

Could you make new release with #64 merged, please? It seems that commit fixes this issue. And this issue is critical.

**Comment by chrfalch** [comment]
Pull Request #64 merged.
