### ISSUE TITLE
Any plans or anyone working towards UWP support?

### ISSUE THREAD

**Issue by tlhintoq** [chrfalch/NControl#59]
I think the title pretty much sums it up.
I was wondering if anyone is working on adding UWP support?
NControl is a really great addition to a Xamarin.Forms project - Whose three big project platforms are iOS, Android and UWP.  **So having this working in UWP would be great!**

**Comment by krisrok** [comment]
for that to work NGraphics has to support UWP which it does not at this moment:
https://github.com/praeclarum/NGraphics/tree/master/Platforms

(though i'm no expert in distinguishing between all those ms-platforms, there are just too many)

**Comment by TomSoderling** [comment]
I've submitted a [PR](https://github.com/praeclarum/NGraphics/pull/63) to NGraphics with that support, and just completed a PR for NControl as well @ #71 
Please, if you could try it out and give feedback, that would be helpful.

**Comment by philipogorman** [comment]
I would love to have this on UWP! @TomSoderling how can I help to test your PR?

**Comment by TomSoderling** [comment]
@philipogorman Thank you, I'd appreciate it. To do that, clone my forked repo from here: https://github.com/MobileComposer/NControl and check out the UWP_Support branch. 
I've updated the readme file with some special instructions for UWP - be sure to look at those.  I believe you'll need Visual Studio 2015. (I'm using the Community version)

**Comment by TomSoderling** [comment]
Good news! The required [NGraphics PR](https://github.com/praeclarum/NGraphics/pull/63) was just merged. Hopefully that will be released soon and this PR can the move forward

**Comment by philipogorman** [comment]
thats great @TomSoderling !
I can't get your branch though, i see it in github, but my desktop git doesn't find it:
$ git branch -r
  origin/Feature/52-ExposePlatformAsProperty
  origin/Feature/UpgradeXamarinForms
  origin/Feature/WindowsPhone81
  origin/HEAD -> origin/develop
  origin/develop
  origin/master
  origin/screenshots

**Comment by TomSoderling** [comment]
That's strange. This is what I have:
$ git branch -r
  origin/Feature/52-ExposePlatformAsProperty
  origin/Feature/UpgradeXamarinForms
  origin/Feature/WindowsPhone81
  origin/HEAD -> origin/develop
  origin/UWP_Support
  origin/develop
  origin/master
  origin/screenshots

Maybe just download the whole repo as a zip?

**Comment by jasells** [comment]
Any ETA on UWP support?

**Comment by dapug** [comment]
Wondering the same. Also finding that the UWP Support branch causes a build failure when referenced in my project.

**Comment by TomSoderling** [comment]
@jasells We're waiting on an official release of NGraphics still - this library depends on that.  I've tried reaching out to praeclarum a few times on twitter, but no response :/

@dapug: Can you elaborate a bit more? I'm using the UWP Support branch in our app right now. You can get it here: https://github.com/MobileComposer/NControl/tree/UWP_Support  Make sure you have the updated NGraphics dlls in a folder named "UWP_NGraphics_Assemblies" at the solution root.

**Comment by chrfalch** [comment]
Pull Request #71  is waiting on release from NGraphics.
