### ISSUE TITLE
NControl resource errors when all packages up to date

### ISSUE THREAD

**Issue by ghost** [chrfalch/NControl#62]
I have a Xamarin.Forms class library solution S1 with a few projects, including an Android project with custom renderers, and a solution S2 with a Xamarin.Forms application referencing assemblies from S1. Solution S1 uses Xamarin.Forms 1.3.3.6323 in some platform-independent projects and Xamarin.Forms 2.2.0.31 in other projects, including the one with Android custom renderers. It uses the version 23.3.0 of the “Xamarin.Android.Support.” packages. Solution S2 uses Xamarin.Forms 2.1.0.6529 and Xamarin.Android.Support. 23.0.1.3 in all projects. Both solutions build, but if I upgrade everything to Xamarin.Forms 2.2.0.45 and Xamarin.Android.Support.\* 23.3.0 and rebuild first solution S1 and then solution S2 referencing already the rebuilt assemblies from S1, then solution S2 does not compile and complains that there are undefined constants in the file “Resource.Designer.cs” in the Android project. I have tried updating the Android SDK to the newest version, cleaning solution S2, deleting all the “bin” and “obj” folders in S2 and removing the file “Resource.Designer.cs” in S2 before rebuilding S2, I even tried emptying the “C:\Users\” + username + “\AppData\Local\Xamarin\zips” folder before rebuilding, but nothing helps, except for reverting to the initial situation. My goal is to unify the versions of Xamarin.Forms and other packages across both solutions, but I have been failing to achieve that for a week already. Maybe I should unify the version of Xamarin.Forms in S1 and S2 to another version than the latest one, but I don’t know how to determine which one to choose. Please, can you help me solve this?

example error: 'Resource.Attribute' does not contain a definition for 'mediaRouteSettingsDrawable'
concerning line in “Resource.Designer.cs”:

```
        global::NControl.Controls.Droid.Resource.Attribute.mediaRouteSettingsDrawable = global::MyCompany.MyApplication.Droid.Resource.Attribute.mediaRouteSettingsDrawable;
```

In the Android project I have all these references:

NControl
NControl.Controls
NControl.Controls.Droid
NControl.Droid
NGraphics
NGraphics.Android

All NuGet packages are up to date.

It is the “MyCompany.MyApplication.Droid.Resource.Attribute” that does not have a member named “mediaRouteSettingsDrawable”. How am I to understand that this member is not generated and at the same time it is expected? How can I fix that? I need to understand this, otherwise I will not move any further.

**Comment by tlhintoq** [comment]
Yep.  This is a known and heavily documented issue on Xamarin forums.
http://forums.xamarin.com/discussion/68085/xamarin-forms-2-2-support-libraries-breaks-some-android-nugets-such-as-ncontrol-and-others#latest

The error message pointing to Resource.Designer.cs is HORRIBLE and leads us all off on a wild goose chase.

The short answer is: Its a major update and its going to break some older NuGets until the people in charge of those NuGets update their packages.  You can either do your own pull, rebuild, then use your local rebuild or wait for the package administrator to get around to it.  

My solution was to drop nControl and just make custom renderers for each platform. I nControl doesn't work on UWP anyway, so I was headed in that direction regardless.  By dropping nControl I then dropped all the dependency NuGets of nGraphics and 3 flavors of SharpDX.  So in the end it wasn't a bad deal.
