### ISSUE TITLE
Does it have multitouch / Touch Move  support on Android?

### ISSUE THREAD

**Issue by slam023** [chrfalch/NControl#67]
Hello,

I have tried using this library but when I tried using touch_began, I can only receive one point. On Touch_Move, the event didn't get call.

**Comment by SimplexAuctor** [comment]
I would also be interested in getting the TouchesMoved and TouchesEnded events on Android.

**Comment by kolodiichyk** [comment]
Agree, on android multitouch not worked...

**Comment by chrfalch** [comment]
Please download the source code and see if you can debug and fix - this
project happily accepts PR's.

Chris

On Fri, Dec 9, 2016 at 8:45 AM, Andriy Kolodiychyk <notifications@github.com

**Comment by kolodiichyk** [comment]
Can't create PR - Request failed with status code: 403

**Comment by kolodiichyk** [comment]
So, In android NControlViewRenderer.OnTouchEvent need to change: 

var touchInfo = new[]{
                new NGraphics.Point(e.GetX() * scale, e.GetY() * scale)
            };

to

var touchInfo = new List<NGraphics.Point>();
            for (var i = 0; i < e.PointerCount; i++)
            {
                var coord = new MotionEvent.PointerCoords();
                e.GetPointerCoords(i, coord);
                touchInfo.Add(new NGraphics.Point(coord.X*scale, coord.Y*scale));
            }

**Comment by kolodiichyk** [comment]
Chris, sorry but I don't have time to investigate problem with creating PR

**Comment by BlueRaja** [comment]
@koland 403-forbidden means you are trying to push/pull a repo you don't have access to.  You have to fork the code into your own repo, fix it, push it (again to your own repo) and then create a PR.

**Comment by kolodiichyk** [comment]
Thx @BlueRaja. I created PR

**Comment by chrfalch** [comment]
Pull Request #72 Merged.
