### ISSUE TITLE
NControl doesn't compile anymore with Xamarin.Forms v2.3.1.114

### ISSUE THREAD

**Issue by Emasoft** [chrfalch/NControl#68]
I was forced to upgrade to the latest **Xamarin.Forms v2.3.1.114** due to a bug of the previous version that was affecting my app. 

Unfortunately now NControl doesn't compile anymore! Those are the errors I get:

**NControl.Droid**
- ERROR 1

_Code giving the error:_

``` C#
     // Perform custom drawing from the NGraphics subsystems
     var ncanvas = new CanvasCanvas(canvas);
```

_Compiler error message:_

```
../NControl/NControl.Droid/NControlViewRenderer.cs(22,22): Error CS0246: The type or namespace name `CanvasCanvas' could not be found. Are you missing an assembly reference? (CS0246) (NControl.Droid)
```
- ERROR 2

_Code giving the error:_

``` C#
/// <summary>
        /// Callback for the OnGetPlatform event in the abstract control
        /// </summary>
        private IPlatform OnGetPlatformHandler ()
        {
            return AndroidPlatform();
        }
```

_Compiler error message:_

```
../NControl/NControl.Droid/NControlViewRenderer.cs(11,11): Error CS0122: `System.AndroidPlatform' is inaccessible due to its protection level (CS0122) (NControl.Droid)
```

**NControl.iOS**
- ERROR 3

_Code giving the error:_

``` C#
var canvas = new CGContextCanvas (context);
```

_Compiler error message:_

```
../NControl/NControl.iOS/NControlViewRenderer.cs(34,34): Error CS0246: The type or namespace name `CGContextCanvas' could not be found. Are you missing an assembly reference? (CS0246) (NControl.iOS)
```
- ERROR 4

_Code giving the error:_

``` C#
        /// <summary>
        /// Callback for the OnGetPlatform event in the abstract control
        /// </summary>
        private IPlatform OnGetPlatformHandler ()
        {
            return new ApplePlatform();
        }

```

Compiler error message:

```
../NControl/NControl.iOS/NControlViewRenderer.cs(24,24): Error CS0246: The type or namespace name `ApplePlatform' could not be found. Are you missing an assembly reference? (CS0246) (NControl.iOS)
```

Is there something I can do to fix those? Unfortunately I cannot revert to the older Xamarin version because there are some fatal issues for my app that the new version fixes.

**Comment by chrfalch** [comment]
I'm building several apps with Xamarin.Forms 2.3.1.114 without any issues. I've also updated packages in the project to test if it builds successfully with the latest XF version without problems.

Closing this issue - please reopen if you have more information.

**Comment by BlueRaja** [comment]
I'm building a slightly older version of NControl with the latest version of Xamarin Forms, with no issues.  I'll try updating NControl tonight to see if I repro.
