### ISSUE TITLE
Android display density

### ISSUE THREAD

**Issue by ghost** [chrfalch/NControl#8]
I've noticed in the demo that while NGraphics.ICanvas appears to work with resolution independent "pixels" on iOS, the Android equivalent works with real pixels.

I haven't yet looked to see what NGraphics offers in this regard, but was wondering whether you think it's something that NControl could/should handle, or if you'd rather leave it up to the control implementations?

p.s. NControl is quite great. Thanks.

**Comment by chrfalch** [comment]
Thanks for your feedback - I need to investigate this a little further.

**Comment by Henkoglobin** [comment]
It's also worth noting that, while drawing on Android is performed using real pixels, touch events are translated to dp. This does not happen on WP (I can't test iOS at the moment), which makes it difficult to handle touch input appropriately.

**Comment by BlueRaja** [comment]
https://github.com/chrfalch/NControl/blob/master/NControl/NControl.Droid/NControlViewRenderer.cs#L103

Why are you converting to dp if `NGraphics` _(on Android)_ works with pixels?  Even doing something as simple as drawing where the user touches is a chore... and I'm not sure how I'd make the code client-independent

**Comment by Henkoglobin** [comment]
> Why are you converting to dp if `NGraphics` _(on Android)_ works with pixels?

Exactly what I was talking about. Touch events should always use the same coordinate space as draw methods.

**Comment by BlueRaja** [comment]
Created a PR: #26

**Comment by chrfalch** [comment]
Merged.
