### ISSUE TITLE
Doesn't seem to work on WP8

### ISSUE THREAD

**Issue by Henkoglobin** [chrfalch/NControl#9]
It seems that drawing does not work on WP8 (or that I'm missing something during the installation :) ). I have created a Xamarin.Forms Portable project, installed NControl via NuGet for all four projects in the solution, and changed the default code as follows:

``` csharp
            MainPage = new ContentPage
            {
                Content = new StackLayout
                {
                    VerticalOptions = LayoutOptions.Center,
                    Children = {
                        new Label {
                            XAlign = TextAlignment.Center,
                            Text = "Welcome to Xamarin Forms!"
                        },
                        new NControlView()
                        {
                            DrawingFunction = (canvas, rect) => {
                                canvas.DrawEllipse(rect, Pens.Red, Brushes.Green);
                            },
                            WidthRequest = 200, HeightRequest = 200
                        }
                    }
                }
            };
```

This works perfectly fine on Android, but does not seem to work for the Windows Phone project. I also tried retargetting the WP project to Windows Phone Silverlight 8.1, but still nothing happens. Is this an issue or am I simply missing something?

**Comment by chrfalch** [comment]
We'll check this and see if we can find a solution - it seems to be working here.

**Comment by Henkoglobin** [comment]
If you need further information or a sample project, do not hesitate to ask for it :) Btw, I've had the chance to work with NControl for a bit (using Android) and it's really great! Keep up the good work :+1:

**Comment by Henkoglobin** [comment]
Sorry, mistake on my part: I forgot to call NControl.WP80.NControlViewRenderer.Init(); in MainPage.xaml.cs...
